### ISSUE TITLE
Cluster Custom Endpoints and cfnOptions.condition

### ISSUE THREAD

**Issue by denkras** [berenddeboer/cdk-rds-sql#45]
I want to say thank for the everyone who made contribution to cdk-rds-sql. 

At this moment i am running into the issue when creating a cluster with cfnOptions conditions. It seems that lambda role requires all the resources to be present even if cfnOptions.condition is false. When deploying the stack i would get an error 

>  FAILED, Template format error: Unresolved resource dependencies [AMSRdsV2ClustertestroD6309B35, AMSRdsV2ClusterReader213D9F703] 

What happens is that provider role adds above dependencies which it shouldn't 

Looking at generated template i see the following 

```
ProviderRdsSqlframeworkonEventServiceRoleE9F0DEE8:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    DependsOn:
      - AMSRdsV2ClusterLogRetentionpostgresqlFB922F06
      - AMSRdsV2ClustertestroD6309B35
```
      
To create this end point i use

```

        //Create Custom EndPoint 
    const testEndPoint = new DatabaseClusterEndpoint(dbCluster, "test-ro", {
      cluster:dbCluster,
      endpointType: DatabaseClusterEndpointType.READER,
      members: DatabaseClusterEndpointMember.include([
        findInstance("Reader").ref,
        findInstance("Reader2").ref,
      ]),
    })
    const testEndPointCfn = testEndPoint.node.findChild('Resource').node.defaultChild as cdk.CfnResource
    testEndPointCfn.cfnOptions.condition = isCustomEnabled


```
